'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { UnopsButton as UnopsButtonElement, defineCustomElement as defineUnopsButton } from "@spectrum/core/dist/components/unops-button.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type UnopsButtonEvents = { onButtonPressed: EventName<CustomEvent<boolean>> };

export const UnopsButton: StencilReactComponent<UnopsButtonElement, UnopsButtonEvents> = /*@__PURE__*/ createComponent<UnopsButtonElement, UnopsButtonEvents>({
    tagName: 'unops-button',
    elementClass: UnopsButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onButtonPressed: 'buttonPressed' } as UnopsButtonEvents,
    defineCustomElement: defineUnopsButton
});
