'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { SpectrumButton as SpectrumButtonElement, defineCustomElement as defineSpectrumButton } from "@unops-itg-npm/cpit-spectrum/dist/components/spectrum-button.js";
import { SpectrumCarousel as SpectrumCarouselElement, defineCustomElement as defineSpectrumCarousel } from "@unops-itg-npm/cpit-spectrum/dist/components/spectrum-carousel.js";
import { SpectrumChip as SpectrumChipElement, defineCustomElement as defineSpectrumChip } from "@unops-itg-npm/cpit-spectrum/dist/components/spectrum-chip.js";
import { SpectrumCollapsibleList as SpectrumCollapsibleListElement, defineCustomElement as defineSpectrumCollapsibleList } from "@unops-itg-npm/cpit-spectrum/dist/components/spectrum-collapsible-list.js";
import { SpectrumContextMenu as SpectrumContextMenuElement, defineCustomElement as defineSpectrumContextMenu } from "@unops-itg-npm/cpit-spectrum/dist/components/spectrum-context-menu.js";
import { SpectrumConversationPanel as SpectrumConversationPanelElement, defineCustomElement as defineSpectrumConversationPanel } from "@unops-itg-npm/cpit-spectrum/dist/components/spectrum-conversation-panel.js";
import { SpectrumMegamenu as SpectrumMegamenuElement, defineCustomElement as defineSpectrumMegamenu } from "@unops-itg-npm/cpit-spectrum/dist/components/spectrum-megamenu.js";
import { SpectrumRailItem as SpectrumRailItemElement, defineCustomElement as defineSpectrumRailItem } from "@unops-itg-npm/cpit-spectrum/dist/components/spectrum-rail-item.js";
import { SpectrumRail as SpectrumRailElement, defineCustomElement as defineSpectrumRail } from "@unops-itg-npm/cpit-spectrum/dist/components/spectrum-rail.js";
import { SpectrumSearchInput as SpectrumSearchInputElement, defineCustomElement as defineSpectrumSearchInput } from "@unops-itg-npm/cpit-spectrum/dist/components/spectrum-search-input.js";
import { SpectrumTheme as SpectrumThemeElement, defineCustomElement as defineSpectrumTheme } from "@unops-itg-npm/cpit-spectrum/dist/components/spectrum-theme.js";
import { SpectrumWallpaper as SpectrumWallpaperElement, defineCustomElement as defineSpectrumWallpaper } from "@unops-itg-npm/cpit-spectrum/dist/components/spectrum-wallpaper.js";
import React from 'react';

type SpectrumButtonEvents = { onButtonAction: EventName<CustomEvent<{ action?: string; label: string }>> };

export const SpectrumButton: StencilReactComponent<SpectrumButtonElement, SpectrumButtonEvents> = /*@__PURE__*/ createComponent<SpectrumButtonElement, SpectrumButtonEvents>({
    tagName: 'spectrum-button',
    elementClass: SpectrumButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onButtonAction: 'buttonAction' } as SpectrumButtonEvents,
    defineCustomElement: defineSpectrumButton
});

type SpectrumCarouselEvents = NonNullable<unknown>;

export const SpectrumCarousel: StencilReactComponent<SpectrumCarouselElement, SpectrumCarouselEvents> = /*@__PURE__*/ createComponent<SpectrumCarouselElement, SpectrumCarouselEvents>({
    tagName: 'spectrum-carousel',
    elementClass: SpectrumCarouselElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SpectrumCarouselEvents,
    defineCustomElement: defineSpectrumCarousel
});

type SpectrumChipEvents = { onChipAction: EventName<CustomEvent<{ action?: string; label: string }>> };

export const SpectrumChip: StencilReactComponent<SpectrumChipElement, SpectrumChipEvents> = /*@__PURE__*/ createComponent<SpectrumChipElement, SpectrumChipEvents>({
    tagName: 'spectrum-chip',
    elementClass: SpectrumChipElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onChipAction: 'chipAction' } as SpectrumChipEvents,
    defineCustomElement: defineSpectrumChip
});

type SpectrumCollapsibleListEvents = {
    onChildAction: EventName<CustomEvent<{ action: string; label: string; }>>,
    onExpandAction: EventName<CustomEvent<{ label: string; }>>,
    onContractAction: EventName<CustomEvent<{ label: string; }>>,
    onContextAction: EventName<CustomEvent<{ value: string; label: string }>>
};

export const SpectrumCollapsibleList: StencilReactComponent<SpectrumCollapsibleListElement, SpectrumCollapsibleListEvents> = /*@__PURE__*/ createComponent<SpectrumCollapsibleListElement, SpectrumCollapsibleListEvents>({
    tagName: 'spectrum-collapsible-list',
    elementClass: SpectrumCollapsibleListElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onChildAction: 'child-action',
        onExpandAction: 'expand-action',
        onContractAction: 'contract-action',
        onContextAction: 'context-action'
    } as SpectrumCollapsibleListEvents,
    defineCustomElement: defineSpectrumCollapsibleList
});

type SpectrumContextMenuEvents = {
    onActionClick: EventName<CustomEvent<{ value: string; targetKey: string }>>,
    onMenuClose: EventName<CustomEvent<void>>
};

export const SpectrumContextMenu: StencilReactComponent<SpectrumContextMenuElement, SpectrumContextMenuEvents> = /*@__PURE__*/ createComponent<SpectrumContextMenuElement, SpectrumContextMenuEvents>({
    tagName: 'spectrum-context-menu',
    elementClass: SpectrumContextMenuElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onActionClick: 'action-click',
        onMenuClose: 'menu-close'
    } as SpectrumContextMenuEvents,
    defineCustomElement: defineSpectrumContextMenu
});

type SpectrumConversationPanelEvents = {
    onExplorationSelected: EventName<CustomEvent<string>>,
    onAction: EventName<CustomEvent<{ type: string, value: string }>>,
    onExplore: EventName<CustomEvent<string>>,
    onSourceClick: EventName<CustomEvent<{ label: string, value: string }>>
};

export const SpectrumConversationPanel: StencilReactComponent<SpectrumConversationPanelElement, SpectrumConversationPanelEvents> = /*@__PURE__*/ createComponent<SpectrumConversationPanelElement, SpectrumConversationPanelEvents>({
    tagName: 'spectrum-conversation-panel',
    elementClass: SpectrumConversationPanelElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onExplorationSelected: 'explorationSelected',
        onAction: 'action',
        onExplore: 'explore',
        onSourceClick: 'sourceClick'
    } as SpectrumConversationPanelEvents,
    defineCustomElement: defineSpectrumConversationPanel
});

type SpectrumMegamenuEvents = NonNullable<unknown>;

export const SpectrumMegamenu: StencilReactComponent<SpectrumMegamenuElement, SpectrumMegamenuEvents> = /*@__PURE__*/ createComponent<SpectrumMegamenuElement, SpectrumMegamenuEvents>({
    tagName: 'spectrum-megamenu',
    elementClass: SpectrumMegamenuElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SpectrumMegamenuEvents,
    defineCustomElement: defineSpectrumMegamenu
});

type SpectrumRailEvents = {
    onExpandedChange: EventName<CustomEvent<boolean>>,
    onSearchChange: EventName<CustomEvent<{ value: string }>>,
    onRailAction: EventName<CustomEvent<{ action: string, label: string }>>,
    onAddAction: EventName<CustomEvent<void>>
};

export const SpectrumRail: StencilReactComponent<SpectrumRailElement, SpectrumRailEvents> = /*@__PURE__*/ createComponent<SpectrumRailElement, SpectrumRailEvents>({
    tagName: 'spectrum-rail',
    elementClass: SpectrumRailElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onExpandedChange: 'expandedChange',
        onSearchChange: 'searchChange',
        onRailAction: 'railAction',
        onAddAction: 'addAction'
    } as SpectrumRailEvents,
    defineCustomElement: defineSpectrumRail
});

type SpectrumRailItemEvents = NonNullable<unknown>;

export const SpectrumRailItem: StencilReactComponent<SpectrumRailItemElement, SpectrumRailItemEvents> = /*@__PURE__*/ createComponent<SpectrumRailItemElement, SpectrumRailItemEvents>({
    tagName: 'spectrum-rail-item',
    elementClass: SpectrumRailItemElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SpectrumRailItemEvents,
    defineCustomElement: defineSpectrumRailItem
});

type SpectrumSearchInputEvents = {
    onSearchSubmit: EventName<CustomEvent<string>>,
    onSearchInput: EventName<CustomEvent<string>>
};

export const SpectrumSearchInput: StencilReactComponent<SpectrumSearchInputElement, SpectrumSearchInputEvents> = /*@__PURE__*/ createComponent<SpectrumSearchInputElement, SpectrumSearchInputEvents>({
    tagName: 'spectrum-search-input',
    elementClass: SpectrumSearchInputElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onSearchSubmit: 'searchSubmit',
        onSearchInput: 'searchInput'
    } as SpectrumSearchInputEvents,
    defineCustomElement: defineSpectrumSearchInput
});

type SpectrumThemeEvents = NonNullable<unknown>;

export const SpectrumTheme: StencilReactComponent<SpectrumThemeElement, SpectrumThemeEvents> = /*@__PURE__*/ createComponent<SpectrumThemeElement, SpectrumThemeEvents>({
    tagName: 'spectrum-theme',
    elementClass: SpectrumThemeElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SpectrumThemeEvents,
    defineCustomElement: defineSpectrumTheme
});

type SpectrumWallpaperEvents = NonNullable<unknown>;

export const SpectrumWallpaper: StencilReactComponent<SpectrumWallpaperElement, SpectrumWallpaperEvents> = /*@__PURE__*/ createComponent<SpectrumWallpaperElement, SpectrumWallpaperEvents>({
    tagName: 'spectrum-wallpaper',
    elementClass: SpectrumWallpaperElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as SpectrumWallpaperEvents,
    defineCustomElement: defineSpectrumWallpaper
});
