
import * as d from './components';

export const DIRECTIVES = [
  d.SpectrumAccordion,
  d.SpectrumAppLayout,
  d.SpectrumApplicationLayout,
  d.SpectrumAvatar,
  d.SpectrumBadge,
  d.SpectrumButton,
  d.SpectrumCard,
  d.SpectrumChip,
  d.SpectrumCluster,
  d.SpectrumCollapsibleList,
  d.SpectrumContainer,
  d.SpectrumContextMenu,
  d.SpectrumConversationPanel,
  d.SpectrumCookieCompliance,
  d.SpectrumDialog,
  d.SpectrumFlex,
  d.SpectrumGrid,
  d.SpectrumHero,
  d.SpectrumImageGallery,
  d.SpectrumMenu,
  d.SpectrumPanel,
  d.SpectrumRail,
  d.SpectrumRailAlternative,
  d.SpectrumRailItem,
  d.SpectrumSearchInput,
  d.SpectrumSearchResults,
  d.SpectrumSelect,
  d.SpectrumSidebar,
  d.SpectrumStack,
  d.SpectrumSwitch,
  d.SpectrumTheme,
  d.SpectrumToast,
  d.SpectrumWallpaper,
  d.SpectrumWizard
];
