/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SpectrumButton {
        "buttonText": string;
        "iconOnly": boolean;
        "leftIcon": string;
        "outline": boolean;
        "rightIcon": string;
        "showButtonText": boolean;
        "showLeftIcon": boolean;
        "showRightIcon": boolean;
        "size": 'sm' | 'base' | 'lg';
        "state": 'default' | 'hover' | 'active' | 'disabled';
        "variant": 'primary' | 'secondary' | 'success' | 'warning' | 'danger';
    }
    interface SpectrumCarousel {
        /**
          * animationtime The time in milliseconds for the slide transition animation Default: 1000
         */
        "animationtime": number;
        /**
          * autoplay  The time in milliseconds between slide transitions 0 indicates no autoplay Default: 0
         */
        "autoplay": number;
        /**
          * content The carousel content as a json structure of slides each with an image, optional link and optiopnal text { "image": "url", "link": "url", "text": "text" } Default: []
         */
        "content": string;
        /**
          * gap The gap between slides in pixels Default: 0
         */
        "gap": number;
        /**
          * hobverpause Pause the carousel when the mouse is over it Default: true
         */
        "hoverpause": boolean;
        /**
          * Show The number of slides to show at once Default: 3
         */
        "show": number;
    }
    interface SpectrumConversationPanel {
        /**
          * The actions to display in the messages Default: null
         */
        "actions": string;
        /**
          * The title to display in the conversation panel Default: null
         */
        "conversationtitle": string;
        /**
          * The messsages to display in the conversation panel Default: null
         */
        "messages": string;
        /**
          * The sources to display in the messages Default: null
         */
        "sources": string;
    }
    interface SpectrumMegamenu {
        /**
          * The megamenu close button icon Default: close
         */
        "closeicon": string;
        /**
          * The megamenu content as a json structure of sections and links sections are objects with a title and links links are an array of objects with a title and href optionally text can be added to a section  with a title and text pair Default: []
         */
        "content": string;
        /**
          * The megamenu title text Default: Mega Menu
         */
        "megamenutitle": string;
        /**
          * The megamenu open button icon Default: menu
         */
        "openicon": string;
        /**
          * A custom width for the megamenu Default: null
         */
        "width": string;
    }
    interface SpectrumWallpaper {
        /**
          * The background value (color, gradient, or image URL)
         */
        "background": string;
        /**
          * The background image position
         */
        "backgroundposition": string;
        /**
          * The background image size
         */
        "backgroundsize": string;
        /**
          * Whether to show the theme color swatches
         */
        "showSwatches": boolean;
    }
}
export interface SpectrumConversationPanelCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSpectrumConversationPanelElement;
}
declare global {
    interface HTMLSpectrumButtonElement extends Components.SpectrumButton, HTMLStencilElement {
    }
    var HTMLSpectrumButtonElement: {
        prototype: HTMLSpectrumButtonElement;
        new (): HTMLSpectrumButtonElement;
    };
    interface HTMLSpectrumCarouselElement extends Components.SpectrumCarousel, HTMLStencilElement {
    }
    var HTMLSpectrumCarouselElement: {
        prototype: HTMLSpectrumCarouselElement;
        new (): HTMLSpectrumCarouselElement;
    };
    interface HTMLSpectrumConversationPanelElementEventMap {
        "explorationSelected": string;
        "action": string;
        "explore": string;
    }
    interface HTMLSpectrumConversationPanelElement extends Components.SpectrumConversationPanel, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSpectrumConversationPanelElementEventMap>(type: K, listener: (this: HTMLSpectrumConversationPanelElement, ev: SpectrumConversationPanelCustomEvent<HTMLSpectrumConversationPanelElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSpectrumConversationPanelElementEventMap>(type: K, listener: (this: HTMLSpectrumConversationPanelElement, ev: SpectrumConversationPanelCustomEvent<HTMLSpectrumConversationPanelElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSpectrumConversationPanelElement: {
        prototype: HTMLSpectrumConversationPanelElement;
        new (): HTMLSpectrumConversationPanelElement;
    };
    interface HTMLSpectrumMegamenuElement extends Components.SpectrumMegamenu, HTMLStencilElement {
    }
    var HTMLSpectrumMegamenuElement: {
        prototype: HTMLSpectrumMegamenuElement;
        new (): HTMLSpectrumMegamenuElement;
    };
    interface HTMLSpectrumWallpaperElement extends Components.SpectrumWallpaper, HTMLStencilElement {
    }
    var HTMLSpectrumWallpaperElement: {
        prototype: HTMLSpectrumWallpaperElement;
        new (): HTMLSpectrumWallpaperElement;
    };
    interface HTMLElementTagNameMap {
        "spectrum-button": HTMLSpectrumButtonElement;
        "spectrum-carousel": HTMLSpectrumCarouselElement;
        "spectrum-conversation-panel": HTMLSpectrumConversationPanelElement;
        "spectrum-megamenu": HTMLSpectrumMegamenuElement;
        "spectrum-wallpaper": HTMLSpectrumWallpaperElement;
    }
}
declare namespace LocalJSX {
    interface SpectrumButton {
        "buttonText"?: string;
        "iconOnly"?: boolean;
        "leftIcon"?: string;
        "outline"?: boolean;
        "rightIcon"?: string;
        "showButtonText"?: boolean;
        "showLeftIcon"?: boolean;
        "showRightIcon"?: boolean;
        "size"?: 'sm' | 'base' | 'lg';
        "state"?: 'default' | 'hover' | 'active' | 'disabled';
        "variant"?: 'primary' | 'secondary' | 'success' | 'warning' | 'danger';
    }
    interface SpectrumCarousel {
        /**
          * animationtime The time in milliseconds for the slide transition animation Default: 1000
         */
        "animationtime"?: number;
        /**
          * autoplay  The time in milliseconds between slide transitions 0 indicates no autoplay Default: 0
         */
        "autoplay"?: number;
        /**
          * content The carousel content as a json structure of slides each with an image, optional link and optiopnal text { "image": "url", "link": "url", "text": "text" } Default: []
         */
        "content"?: string;
        /**
          * gap The gap between slides in pixels Default: 0
         */
        "gap"?: number;
        /**
          * hobverpause Pause the carousel when the mouse is over it Default: true
         */
        "hoverpause"?: boolean;
        /**
          * Show The number of slides to show at once Default: 3
         */
        "show"?: number;
    }
    interface SpectrumConversationPanel {
        /**
          * The actions to display in the messages Default: null
         */
        "actions"?: string;
        /**
          * The title to display in the conversation panel Default: null
         */
        "conversationtitle"?: string;
        /**
          * The messsages to display in the conversation panel Default: null
         */
        "messages"?: string;
        "onAction"?: (event: SpectrumConversationPanelCustomEvent<string>) => void;
        "onExplorationSelected"?: (event: SpectrumConversationPanelCustomEvent<string>) => void;
        "onExplore"?: (event: SpectrumConversationPanelCustomEvent<string>) => void;
        /**
          * The sources to display in the messages Default: null
         */
        "sources"?: string;
    }
    interface SpectrumMegamenu {
        /**
          * The megamenu close button icon Default: close
         */
        "closeicon"?: string;
        /**
          * The megamenu content as a json structure of sections and links sections are objects with a title and links links are an array of objects with a title and href optionally text can be added to a section  with a title and text pair Default: []
         */
        "content"?: string;
        /**
          * The megamenu title text Default: Mega Menu
         */
        "megamenutitle"?: string;
        /**
          * The megamenu open button icon Default: menu
         */
        "openicon"?: string;
        /**
          * A custom width for the megamenu Default: null
         */
        "width"?: string;
    }
    interface SpectrumWallpaper {
        /**
          * The background value (color, gradient, or image URL)
         */
        "background"?: string;
        /**
          * The background image position
         */
        "backgroundposition"?: string;
        /**
          * The background image size
         */
        "backgroundsize"?: string;
        /**
          * Whether to show the theme color swatches
         */
        "showSwatches"?: boolean;
    }
    interface IntrinsicElements {
        "spectrum-button": SpectrumButton;
        "spectrum-carousel": SpectrumCarousel;
        "spectrum-conversation-panel": SpectrumConversationPanel;
        "spectrum-megamenu": SpectrumMegamenu;
        "spectrum-wallpaper": SpectrumWallpaper;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "spectrum-button": LocalJSX.SpectrumButton & JSXBase.HTMLAttributes<HTMLSpectrumButtonElement>;
            "spectrum-carousel": LocalJSX.SpectrumCarousel & JSXBase.HTMLAttributes<HTMLSpectrumCarouselElement>;
            "spectrum-conversation-panel": LocalJSX.SpectrumConversationPanel & JSXBase.HTMLAttributes<HTMLSpectrumConversationPanelElement>;
            "spectrum-megamenu": LocalJSX.SpectrumMegamenu & JSXBase.HTMLAttributes<HTMLSpectrumMegamenuElement>;
            "spectrum-wallpaper": LocalJSX.SpectrumWallpaper & JSXBase.HTMLAttributes<HTMLSpectrumWallpaperElement>;
        }
    }
}
