/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CollapsibleListItem } from "./components/spectrum-collapsible-list/spectrum-collapsible-list";
import { ContextMenuAction } from "./components/spectrum-context-menu/spectrum-context-menu";
export { CollapsibleListItem } from "./components/spectrum-collapsible-list/spectrum-collapsible-list";
export { ContextMenuAction } from "./components/spectrum-context-menu/spectrum-context-menu";
export namespace Components {
    /**
     * Spectrum Button Component
     * A versatile button component with multiple variants, sizes, and states.
     * Supports icons, text, and various interactive states.
     */
    interface SpectrumButton {
        "action": string;
        "buttonText": string;
        "debug": boolean;
        "disabled": boolean;
        "iconOnly": boolean;
        "leftIcon": string;
        "outline": boolean;
        "rightIcon": string;
        "ripple": boolean;
        "showButtonText": boolean;
        "showLeftIcon": boolean;
        "showRightIcon": boolean;
        "size": 'sm' | 'base' | 'lg';
        "state": 'default' | 'hover' | 'active' | 'disabled';
        "variant": 'primary' | 'secondary' | 'success' | 'warning' | 'danger' | 'ghost' | 'outline' | 'fab';
    }
    interface SpectrumCarousel {
        /**
          * animationtime The time in milliseconds for the slide transition animation Default: 1000
         */
        "animationtime": number;
        /**
          * autoplay  The time in milliseconds between slide transitions 0 indicates no autoplay Default: 0
         */
        "autoplay": number;
        /**
          * content The carousel content as a json structure of slides each with an image, optional link and optiopnal text { "image": "url", "link": "url", "text": "text" } Default: []
         */
        "content": string;
        /**
          * gap The gap between slides in pixels Default: 0
         */
        "gap": number;
        /**
          * hobverpause Pause the carousel when the mouse is over it Default: true
         */
        "hoverpause": boolean;
        /**
          * Show The number of slides to show at once Default: 3
         */
        "show": number;
    }
    /**
     * Spectrum Chip Component
     * A versatile chip component that can be used for tags, filters, and selections.
     * Supports leading/trailing icons, selection states, and various interactive behaviors.
     */
    interface SpectrumChip {
        "action": string;
        "debug": boolean;
        "disabled": boolean;
        "label": string;
        "leadingIcon": string;
        "outline": boolean;
        "ripple": boolean;
        "selected": boolean;
        "showTrailingIcon": boolean;
        "trailingIcon": string;
        "variant": 'primary' | 'secondary' | 'assist' | 'filter' | 'input' | 'suggestion';
    }
    interface SpectrumCollapsibleList {
        /**
          * Context actions for all leaf nodes
         */
        "contextActions": ContextMenuAction[];
        /**
          * Filter value to filter list items
         */
        "filter": string;
        /**
          * The nested data structure for the list
         */
        "items": CollapsibleListItem[];
        /**
          * Controls whether expanding one parent collapses other parents at the same level Default is true (mutually exclusive expansion)
         */
        "mutuallyExclusive": boolean;
    }
    /**
     * Spectrum Context Menu Component
     * A popup menu for contextual actions that can be attached to any element.
     */
    interface SpectrumContextMenu {
        "hide": () => Promise<void>;
        /**
          * The key identifying the target component that triggered this menu
         */
        "position": 'left' | 'right' | 'top' | 'bottom';
        /**
          * Position the menu at specific coordinates
         */
        "positionAtCoordinates": (x: number, y: number) => Promise<boolean>;
        "show": (actions: any[], x: number, y: number, targetKey: string) => Promise<void>;
    }
    interface SpectrumConversationPanel {
        /**
          * The actions to display in the messages Default: null
         */
        "actions": string;
        /**
          * The title to display in the conversation panel Default: null
         */
        "conversationtitle": string;
        /**
          * The messsages to display in the conversation panel Default: null
         */
        "messages": string;
        /**
          * Scrolls the conversation panel to the latest message
         */
        "scrollToLatest": () => Promise<void>;
        /**
          * The sources to display in the messages Default: null
         */
        "sources": string;
    }
    interface SpectrumMegamenu {
        /**
          * The megamenu close button icon Default: close
         */
        "closeicon": string;
        /**
          * The megamenu content as a json structure of sections and links sections are objects with a title and links links are an array of objects with a title and href optionally text can be added to a section  with a title and text pair Default: []
         */
        "content": string;
        /**
          * The megamenu title text Default: Mega Menu
         */
        "megamenutitle": string;
        /**
          * The megamenu open button icon Default: menu
         */
        "openicon": string;
        /**
          * A custom width for the megamenu Default: null
         */
        "width": string;
    }
    /**
     * Spectrum Rail Component
     * A vertical navigation rail with two states: expanded and contracted
     */
    interface SpectrumRail {
        /**
          * Add button label (displayed in expanded state)
         */
        "addLabel": string;
        /**
          * Application name to display in expanded menu
         */
        "appName": string;
        /**
          * Expanded width for the rail (with units like px, rem, etc.)
         */
        "expandedWidth": string;
        /**
          * Whether the rail should be initially expanded
         */
        "initialExpanded": boolean;
        /**
          * More section label (displayed in expanded state)
         */
        "moreLabel": string;
        /**
          * Method that can be called by parent components to programmatically  control the expanded state
         */
        "setExpanded": (expanded: boolean) => Promise<boolean>;
        /**
          * Method to programmatically control the add button visibility
         */
        "setShowAddButton": (show: boolean) => Promise<boolean>;
        /**
          * Whether to show the add button in the rail
         */
        "showAddButton": boolean;
    }
    /**
     * Spectrum Rail Item Component
     * A component designed to work within the rail that automatically
     * switches between icon-only and full display modes
     */
    interface SpectrumRailItem {
        /**
          * Optional action identifier
         */
        "action"?: string;
        /**
          * Current expanded state
         */
        "expanded": boolean;
        /**
          * The icon to display
         */
        "icon": string;
        /**
          * The label to display
         */
        "label": string;
        /**
          * Callback for when rail expansion state changes
         */
        "onRailExpandedChange": (expanded: boolean) => Promise<boolean>;
    }
    interface SpectrumSearchInput {
        /**
          * Whether to enable voice input capabilities (speech recognition)
         */
        "enableVoiceInput": boolean;
        "maxLines": number;
        /**
          * Placeholder text for the search input
         */
        "placeholder": string;
        "setFocus": () => Promise<void>;
    }
    interface SpectrumTheme {
        /**
          * The primary color to generate the theme from Can be any valid CSS color (hex, rgb, hsl)
         */
        "color": string;
        /**
          * Theme configuration object for custom overrides
         */
        "config": string;
        /**
          * Whether to use dark mode
         */
        "dark": boolean;
        /**
          * Whether to show theme color swatches (useful for development)
         */
        "showSwatches": boolean;
    }
    interface SpectrumWallpaper {
        /**
          * The background value (color, gradient, or image URL)
         */
        "background": string;
        /**
          * The background image position
         */
        "backgroundposition": string;
        /**
          * The background image size
         */
        "backgroundsize": string;
        /**
          * Whether to show the theme color swatches
         */
        "showSwatches": boolean;
    }
}
export interface SpectrumButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSpectrumButtonElement;
}
export interface SpectrumChipCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSpectrumChipElement;
}
export interface SpectrumCollapsibleListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSpectrumCollapsibleListElement;
}
export interface SpectrumContextMenuCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSpectrumContextMenuElement;
}
export interface SpectrumConversationPanelCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSpectrumConversationPanelElement;
}
export interface SpectrumRailCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSpectrumRailElement;
}
export interface SpectrumSearchInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSpectrumSearchInputElement;
}
declare global {
    interface HTMLSpectrumButtonElementEventMap {
        "buttonAction": { action?: string; label: string };
    }
    /**
     * Spectrum Button Component
     * A versatile button component with multiple variants, sizes, and states.
     * Supports icons, text, and various interactive states.
     */
    interface HTMLSpectrumButtonElement extends Components.SpectrumButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSpectrumButtonElementEventMap>(type: K, listener: (this: HTMLSpectrumButtonElement, ev: SpectrumButtonCustomEvent<HTMLSpectrumButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSpectrumButtonElementEventMap>(type: K, listener: (this: HTMLSpectrumButtonElement, ev: SpectrumButtonCustomEvent<HTMLSpectrumButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSpectrumButtonElement: {
        prototype: HTMLSpectrumButtonElement;
        new (): HTMLSpectrumButtonElement;
    };
    interface HTMLSpectrumCarouselElement extends Components.SpectrumCarousel, HTMLStencilElement {
    }
    var HTMLSpectrumCarouselElement: {
        prototype: HTMLSpectrumCarouselElement;
        new (): HTMLSpectrumCarouselElement;
    };
    interface HTMLSpectrumChipElementEventMap {
        "chipAction": { action?: string; label: string };
    }
    /**
     * Spectrum Chip Component
     * A versatile chip component that can be used for tags, filters, and selections.
     * Supports leading/trailing icons, selection states, and various interactive behaviors.
     */
    interface HTMLSpectrumChipElement extends Components.SpectrumChip, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSpectrumChipElementEventMap>(type: K, listener: (this: HTMLSpectrumChipElement, ev: SpectrumChipCustomEvent<HTMLSpectrumChipElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSpectrumChipElementEventMap>(type: K, listener: (this: HTMLSpectrumChipElement, ev: SpectrumChipCustomEvent<HTMLSpectrumChipElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSpectrumChipElement: {
        prototype: HTMLSpectrumChipElement;
        new (): HTMLSpectrumChipElement;
    };
    interface HTMLSpectrumCollapsibleListElementEventMap {
        "child-action": { action: string; label: string; };
        "expand-action": { label: string; };
        "contract-action": { label: string; };
        "context-action": { value: string; label: string };
    }
    interface HTMLSpectrumCollapsibleListElement extends Components.SpectrumCollapsibleList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSpectrumCollapsibleListElementEventMap>(type: K, listener: (this: HTMLSpectrumCollapsibleListElement, ev: SpectrumCollapsibleListCustomEvent<HTMLSpectrumCollapsibleListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSpectrumCollapsibleListElementEventMap>(type: K, listener: (this: HTMLSpectrumCollapsibleListElement, ev: SpectrumCollapsibleListCustomEvent<HTMLSpectrumCollapsibleListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSpectrumCollapsibleListElement: {
        prototype: HTMLSpectrumCollapsibleListElement;
        new (): HTMLSpectrumCollapsibleListElement;
    };
    interface HTMLSpectrumContextMenuElementEventMap {
        "action-click": { value: string; targetKey: string };
        "menu-close": void;
    }
    /**
     * Spectrum Context Menu Component
     * A popup menu for contextual actions that can be attached to any element.
     */
    interface HTMLSpectrumContextMenuElement extends Components.SpectrumContextMenu, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSpectrumContextMenuElementEventMap>(type: K, listener: (this: HTMLSpectrumContextMenuElement, ev: SpectrumContextMenuCustomEvent<HTMLSpectrumContextMenuElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSpectrumContextMenuElementEventMap>(type: K, listener: (this: HTMLSpectrumContextMenuElement, ev: SpectrumContextMenuCustomEvent<HTMLSpectrumContextMenuElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSpectrumContextMenuElement: {
        prototype: HTMLSpectrumContextMenuElement;
        new (): HTMLSpectrumContextMenuElement;
    };
    interface HTMLSpectrumConversationPanelElementEventMap {
        "explorationSelected": string;
        "action": {type: string, value: string};
        "explore": string;
        "sourceClick": {label: string, value: string};
    }
    interface HTMLSpectrumConversationPanelElement extends Components.SpectrumConversationPanel, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSpectrumConversationPanelElementEventMap>(type: K, listener: (this: HTMLSpectrumConversationPanelElement, ev: SpectrumConversationPanelCustomEvent<HTMLSpectrumConversationPanelElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSpectrumConversationPanelElementEventMap>(type: K, listener: (this: HTMLSpectrumConversationPanelElement, ev: SpectrumConversationPanelCustomEvent<HTMLSpectrumConversationPanelElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSpectrumConversationPanelElement: {
        prototype: HTMLSpectrumConversationPanelElement;
        new (): HTMLSpectrumConversationPanelElement;
    };
    interface HTMLSpectrumMegamenuElement extends Components.SpectrumMegamenu, HTMLStencilElement {
    }
    var HTMLSpectrumMegamenuElement: {
        prototype: HTMLSpectrumMegamenuElement;
        new (): HTMLSpectrumMegamenuElement;
    };
    interface HTMLSpectrumRailElementEventMap {
        "expandedChange": boolean;
        "searchChange": { value: string };
        "railAction": { action: string, label: string };
        "addAction": void;
    }
    /**
     * Spectrum Rail Component
     * A vertical navigation rail with two states: expanded and contracted
     */
    interface HTMLSpectrumRailElement extends Components.SpectrumRail, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSpectrumRailElementEventMap>(type: K, listener: (this: HTMLSpectrumRailElement, ev: SpectrumRailCustomEvent<HTMLSpectrumRailElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSpectrumRailElementEventMap>(type: K, listener: (this: HTMLSpectrumRailElement, ev: SpectrumRailCustomEvent<HTMLSpectrumRailElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSpectrumRailElement: {
        prototype: HTMLSpectrumRailElement;
        new (): HTMLSpectrumRailElement;
    };
    /**
     * Spectrum Rail Item Component
     * A component designed to work within the rail that automatically
     * switches between icon-only and full display modes
     */
    interface HTMLSpectrumRailItemElement extends Components.SpectrumRailItem, HTMLStencilElement {
    }
    var HTMLSpectrumRailItemElement: {
        prototype: HTMLSpectrumRailItemElement;
        new (): HTMLSpectrumRailItemElement;
    };
    interface HTMLSpectrumSearchInputElementEventMap {
        "searchSubmit": string;
        "searchInput": string;
    }
    interface HTMLSpectrumSearchInputElement extends Components.SpectrumSearchInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSpectrumSearchInputElementEventMap>(type: K, listener: (this: HTMLSpectrumSearchInputElement, ev: SpectrumSearchInputCustomEvent<HTMLSpectrumSearchInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSpectrumSearchInputElementEventMap>(type: K, listener: (this: HTMLSpectrumSearchInputElement, ev: SpectrumSearchInputCustomEvent<HTMLSpectrumSearchInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSpectrumSearchInputElement: {
        prototype: HTMLSpectrumSearchInputElement;
        new (): HTMLSpectrumSearchInputElement;
    };
    interface HTMLSpectrumThemeElement extends Components.SpectrumTheme, HTMLStencilElement {
    }
    var HTMLSpectrumThemeElement: {
        prototype: HTMLSpectrumThemeElement;
        new (): HTMLSpectrumThemeElement;
    };
    interface HTMLSpectrumWallpaperElement extends Components.SpectrumWallpaper, HTMLStencilElement {
    }
    var HTMLSpectrumWallpaperElement: {
        prototype: HTMLSpectrumWallpaperElement;
        new (): HTMLSpectrumWallpaperElement;
    };
    interface HTMLElementTagNameMap {
        "spectrum-button": HTMLSpectrumButtonElement;
        "spectrum-carousel": HTMLSpectrumCarouselElement;
        "spectrum-chip": HTMLSpectrumChipElement;
        "spectrum-collapsible-list": HTMLSpectrumCollapsibleListElement;
        "spectrum-context-menu": HTMLSpectrumContextMenuElement;
        "spectrum-conversation-panel": HTMLSpectrumConversationPanelElement;
        "spectrum-megamenu": HTMLSpectrumMegamenuElement;
        "spectrum-rail": HTMLSpectrumRailElement;
        "spectrum-rail-item": HTMLSpectrumRailItemElement;
        "spectrum-search-input": HTMLSpectrumSearchInputElement;
        "spectrum-theme": HTMLSpectrumThemeElement;
        "spectrum-wallpaper": HTMLSpectrumWallpaperElement;
    }
}
declare namespace LocalJSX {
    /**
     * Spectrum Button Component
     * A versatile button component with multiple variants, sizes, and states.
     * Supports icons, text, and various interactive states.
     */
    interface SpectrumButton {
        "action"?: string;
        "buttonText"?: string;
        "debug"?: boolean;
        "disabled"?: boolean;
        "iconOnly"?: boolean;
        "leftIcon"?: string;
        "onButtonAction"?: (event: SpectrumButtonCustomEvent<{ action?: string; label: string }>) => void;
        "outline"?: boolean;
        "rightIcon"?: string;
        "ripple"?: boolean;
        "showButtonText"?: boolean;
        "showLeftIcon"?: boolean;
        "showRightIcon"?: boolean;
        "size"?: 'sm' | 'base' | 'lg';
        "state"?: 'default' | 'hover' | 'active' | 'disabled';
        "variant"?: 'primary' | 'secondary' | 'success' | 'warning' | 'danger' | 'ghost' | 'outline' | 'fab';
    }
    interface SpectrumCarousel {
        /**
          * animationtime The time in milliseconds for the slide transition animation Default: 1000
         */
        "animationtime"?: number;
        /**
          * autoplay  The time in milliseconds between slide transitions 0 indicates no autoplay Default: 0
         */
        "autoplay"?: number;
        /**
          * content The carousel content as a json structure of slides each with an image, optional link and optiopnal text { "image": "url", "link": "url", "text": "text" } Default: []
         */
        "content"?: string;
        /**
          * gap The gap between slides in pixels Default: 0
         */
        "gap"?: number;
        /**
          * hobverpause Pause the carousel when the mouse is over it Default: true
         */
        "hoverpause"?: boolean;
        /**
          * Show The number of slides to show at once Default: 3
         */
        "show"?: number;
    }
    /**
     * Spectrum Chip Component
     * A versatile chip component that can be used for tags, filters, and selections.
     * Supports leading/trailing icons, selection states, and various interactive behaviors.
     */
    interface SpectrumChip {
        "action"?: string;
        "debug"?: boolean;
        "disabled"?: boolean;
        "label"?: string;
        "leadingIcon"?: string;
        "onChipAction"?: (event: SpectrumChipCustomEvent<{ action?: string; label: string }>) => void;
        "outline"?: boolean;
        "ripple"?: boolean;
        "selected"?: boolean;
        "showTrailingIcon"?: boolean;
        "trailingIcon"?: string;
        "variant"?: 'primary' | 'secondary' | 'assist' | 'filter' | 'input' | 'suggestion';
    }
    interface SpectrumCollapsibleList {
        /**
          * Context actions for all leaf nodes
         */
        "contextActions"?: ContextMenuAction[];
        /**
          * Filter value to filter list items
         */
        "filter"?: string;
        /**
          * The nested data structure for the list
         */
        "items"?: CollapsibleListItem[];
        /**
          * Controls whether expanding one parent collapses other parents at the same level Default is true (mutually exclusive expansion)
         */
        "mutuallyExclusive"?: boolean;
        /**
          * Event emitted when a child node is clicked
         */
        "onChild-action"?: (event: SpectrumCollapsibleListCustomEvent<{ action: string; label: string; }>) => void;
        /**
          * Event emitted when a context action is clicked
         */
        "onContext-action"?: (event: SpectrumCollapsibleListCustomEvent<{ value: string; label: string }>) => void;
        /**
          * Event emitted when a parent node is contracted
         */
        "onContract-action"?: (event: SpectrumCollapsibleListCustomEvent<{ label: string; }>) => void;
        /**
          * Event emitted when a parent node is expanded
         */
        "onExpand-action"?: (event: SpectrumCollapsibleListCustomEvent<{ label: string; }>) => void;
    }
    /**
     * Spectrum Context Menu Component
     * A popup menu for contextual actions that can be attached to any element.
     */
    interface SpectrumContextMenu {
        /**
          * Event emitted when an action is clicked
         */
        "onAction-click"?: (event: SpectrumContextMenuCustomEvent<{ value: string; targetKey: string }>) => void;
        /**
          * Event emitted when the menu is closed
         */
        "onMenu-close"?: (event: SpectrumContextMenuCustomEvent<void>) => void;
        /**
          * The key identifying the target component that triggered this menu
         */
        "position"?: 'left' | 'right' | 'top' | 'bottom';
    }
    interface SpectrumConversationPanel {
        /**
          * The actions to display in the messages Default: null
         */
        "actions"?: string;
        /**
          * The title to display in the conversation panel Default: null
         */
        "conversationtitle"?: string;
        /**
          * The messsages to display in the conversation panel Default: null
         */
        "messages"?: string;
        "onAction"?: (event: SpectrumConversationPanelCustomEvent<{type: string, value: string}>) => void;
        "onExplorationSelected"?: (event: SpectrumConversationPanelCustomEvent<string>) => void;
        "onExplore"?: (event: SpectrumConversationPanelCustomEvent<string>) => void;
        "onSourceClick"?: (event: SpectrumConversationPanelCustomEvent<{label: string, value: string}>) => void;
        /**
          * The sources to display in the messages Default: null
         */
        "sources"?: string;
    }
    interface SpectrumMegamenu {
        /**
          * The megamenu close button icon Default: close
         */
        "closeicon"?: string;
        /**
          * The megamenu content as a json structure of sections and links sections are objects with a title and links links are an array of objects with a title and href optionally text can be added to a section  with a title and text pair Default: []
         */
        "content"?: string;
        /**
          * The megamenu title text Default: Mega Menu
         */
        "megamenutitle"?: string;
        /**
          * The megamenu open button icon Default: menu
         */
        "openicon"?: string;
        /**
          * A custom width for the megamenu Default: null
         */
        "width"?: string;
    }
    /**
     * Spectrum Rail Component
     * A vertical navigation rail with two states: expanded and contracted
     */
    interface SpectrumRail {
        /**
          * Add button label (displayed in expanded state)
         */
        "addLabel"?: string;
        /**
          * Application name to display in expanded menu
         */
        "appName"?: string;
        /**
          * Expanded width for the rail (with units like px, rem, etc.)
         */
        "expandedWidth"?: string;
        /**
          * Whether the rail should be initially expanded
         */
        "initialExpanded"?: boolean;
        /**
          * More section label (displayed in expanded state)
         */
        "moreLabel"?: string;
        /**
          * Emits when the add button is clicked
         */
        "onAddAction"?: (event: SpectrumRailCustomEvent<void>) => void;
        /**
          * Emits when the rail changes expanded state
         */
        "onExpandedChange"?: (event: SpectrumRailCustomEvent<boolean>) => void;
        /**
          * Emits when a rail action is triggered
         */
        "onRailAction"?: (event: SpectrumRailCustomEvent<{ action: string, label: string }>) => void;
        /**
          * Emits when the search value changes
         */
        "onSearchChange"?: (event: SpectrumRailCustomEvent<{ value: string }>) => void;
        /**
          * Whether to show the add button in the rail
         */
        "showAddButton"?: boolean;
    }
    /**
     * Spectrum Rail Item Component
     * A component designed to work within the rail that automatically
     * switches between icon-only and full display modes
     */
    interface SpectrumRailItem {
        /**
          * Optional action identifier
         */
        "action"?: string;
        /**
          * Current expanded state
         */
        "expanded"?: boolean;
        /**
          * The icon to display
         */
        "icon": string;
        /**
          * The label to display
         */
        "label": string;
    }
    interface SpectrumSearchInput {
        /**
          * Whether to enable voice input capabilities (speech recognition)
         */
        "enableVoiceInput"?: boolean;
        "maxLines"?: number;
        /**
          * Emits when input value changes, for real-time filtering
         */
        "onSearchInput"?: (event: SpectrumSearchInputCustomEvent<string>) => void;
        "onSearchSubmit"?: (event: SpectrumSearchInputCustomEvent<string>) => void;
        /**
          * Placeholder text for the search input
         */
        "placeholder"?: string;
    }
    interface SpectrumTheme {
        /**
          * The primary color to generate the theme from Can be any valid CSS color (hex, rgb, hsl)
         */
        "color"?: string;
        /**
          * Theme configuration object for custom overrides
         */
        "config"?: string;
        /**
          * Whether to use dark mode
         */
        "dark"?: boolean;
        /**
          * Whether to show theme color swatches (useful for development)
         */
        "showSwatches"?: boolean;
    }
    interface SpectrumWallpaper {
        /**
          * The background value (color, gradient, or image URL)
         */
        "background"?: string;
        /**
          * The background image position
         */
        "backgroundposition"?: string;
        /**
          * The background image size
         */
        "backgroundsize"?: string;
        /**
          * Whether to show the theme color swatches
         */
        "showSwatches"?: boolean;
    }
    interface IntrinsicElements {
        "spectrum-button": SpectrumButton;
        "spectrum-carousel": SpectrumCarousel;
        "spectrum-chip": SpectrumChip;
        "spectrum-collapsible-list": SpectrumCollapsibleList;
        "spectrum-context-menu": SpectrumContextMenu;
        "spectrum-conversation-panel": SpectrumConversationPanel;
        "spectrum-megamenu": SpectrumMegamenu;
        "spectrum-rail": SpectrumRail;
        "spectrum-rail-item": SpectrumRailItem;
        "spectrum-search-input": SpectrumSearchInput;
        "spectrum-theme": SpectrumTheme;
        "spectrum-wallpaper": SpectrumWallpaper;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Spectrum Button Component
             * A versatile button component with multiple variants, sizes, and states.
             * Supports icons, text, and various interactive states.
             */
            "spectrum-button": LocalJSX.SpectrumButton & JSXBase.HTMLAttributes<HTMLSpectrumButtonElement>;
            "spectrum-carousel": LocalJSX.SpectrumCarousel & JSXBase.HTMLAttributes<HTMLSpectrumCarouselElement>;
            /**
             * Spectrum Chip Component
             * A versatile chip component that can be used for tags, filters, and selections.
             * Supports leading/trailing icons, selection states, and various interactive behaviors.
             */
            "spectrum-chip": LocalJSX.SpectrumChip & JSXBase.HTMLAttributes<HTMLSpectrumChipElement>;
            "spectrum-collapsible-list": LocalJSX.SpectrumCollapsibleList & JSXBase.HTMLAttributes<HTMLSpectrumCollapsibleListElement>;
            /**
             * Spectrum Context Menu Component
             * A popup menu for contextual actions that can be attached to any element.
             */
            "spectrum-context-menu": LocalJSX.SpectrumContextMenu & JSXBase.HTMLAttributes<HTMLSpectrumContextMenuElement>;
            "spectrum-conversation-panel": LocalJSX.SpectrumConversationPanel & JSXBase.HTMLAttributes<HTMLSpectrumConversationPanelElement>;
            "spectrum-megamenu": LocalJSX.SpectrumMegamenu & JSXBase.HTMLAttributes<HTMLSpectrumMegamenuElement>;
            /**
             * Spectrum Rail Component
             * A vertical navigation rail with two states: expanded and contracted
             */
            "spectrum-rail": LocalJSX.SpectrumRail & JSXBase.HTMLAttributes<HTMLSpectrumRailElement>;
            /**
             * Spectrum Rail Item Component
             * A component designed to work within the rail that automatically
             * switches between icon-only and full display modes
             */
            "spectrum-rail-item": LocalJSX.SpectrumRailItem & JSXBase.HTMLAttributes<HTMLSpectrumRailItemElement>;
            "spectrum-search-input": LocalJSX.SpectrumSearchInput & JSXBase.HTMLAttributes<HTMLSpectrumSearchInputElement>;
            "spectrum-theme": LocalJSX.SpectrumTheme & JSXBase.HTMLAttributes<HTMLSpectrumThemeElement>;
            "spectrum-wallpaper": LocalJSX.SpectrumWallpaper & JSXBase.HTMLAttributes<HTMLSpectrumWallpaperElement>;
        }
    }
}
